### ISSUE TITLE
Training code for V2

### ISSUE THREAD

**Issue by wshuai190** [getao/icae#12]
Hi, sorry if this is already included in the code already, may I ask if you have training cod for v2? (pretraining/fine-tuning), so I can try to reproduce? Thank you very much!

**Comment by getao** [comment]
Thank you for your interest. I'll try to update the training part this week.

**Comment by wshuai190** [comment]
thank you very much! looking forward to this!

**Comment by getao** [comment]
> thank you very much! looking forward to this!

added

**Comment by Bala93** [comment]
Hi, can you share the script to run the python code ?

**Comment by Luowaterbi** [comment]
> Hi, can you share the script to run the python code ?

Really need, too~ Thanks~

**Comment by Bala93** [comment]
This can be helpful 

`torchrun --nproc_per_node 8 instruction_finetune.py --mean_compression_rate $mean_compression_rate --model_max_length $maxlen --fixed_mem_size $mem --lora_r $r --output_dir $ICAE_MODEL_PATH --model_name_or_path $BASE_MODEL --bf16 --train True --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --data_path $data_path --restore_from $PRETRAINED_MODEL --disable_tqdm True --save_steps 2500 --save_total_limit 1 --report_to none`
