### ISSUE TITLE
Pretraining dataset for icae

### ISSUE THREAD

**Issue by Frankstein73** [getao/icae#13]
Hello, thanks for the awesome work you did! Could you please clarify whether ICAE uses the **entire Pile dataset** during its pretraining phase, or if it only utilizes a **subset** of it?

**Comment by getao** [comment]
We used the entire dataset. However, we only train the ICAE with tens of billion tokens.

**Comment by RewindL** [comment]
> We used the entire dataset. However, we only train the ICAE with tens of billion tokens.

Thanks for your excellent work. Can you release pre-training dataset, please? Or specify how to process original pile dataset ? For example, have you filter out  too short/long sequences, or re-combine 10B tokens to long sequence (as 6K/8K tokens) for training as ICAE aims to compress context which is helpful for long context generation.
 
 I am eagerly looking forward to your reply and appreciate if more details can be provided.
