### ISSUE TITLE
Dimension mismatch error while trying Instruction tuning

### ISSUE THREAD

**Issue by Bala93** [getao/icae#19]
Thanks for your work. I am receiving the following error "ValueError: expected sequence of length 142 at dim 1 (got 158)". I think it is due to the following lines
https://github.com/getao/icae/blob/main/code/icae_v2/training_utils.py#L126-L132

where we don't truncate or padding, any suggestions ?

**Comment by Bala93** [comment]
If the batch size is more than 1, dynamic padding function has to be used.

**Comment by ruoyuxie** [comment]
Hi I have the same error. Could you share your workaround for the instruction finetuning?
