### ISSUE TITLE
Decoder in ICAE is not frozen

### ISSUE THREAD

**Issue by fafeeeeee** [getao/icae#4]
Thank you for your work. However, I found that the implementation of ICAE is not the same as described in the paper.

As introduced in the paper, ICAE only uses LoRa in the encoder and freezes the decoder.
<img width="803" alt="image" src="https://github.com/getao/icae/assets/129859769/b10dbd0f-bccf-4630-a7f3-fb05495db37b">

But in the code, LoRA+LLaMA is used as the decoder:
https://github.com/getao/icae/blob/ac08ffbfa35430efd06b50518f1c9e60d57af97f/code/icae/llama_icae_modeling.py#L114
https://github.com/getao/icae/blob/ac08ffbfa35430efd06b50518f1c9e60d57af97f/code/icae/llama_icae_modeling.py#L157-L160

**Comment by fafeeeeee** [comment]
I also found it very difficult to achieve convergence with ICAE when freezing LLM as the decoder, like below:
```python
with self.icae.disable_adapter():
    decoder_outputs = self.icae(inputs_embeds=decoder_input_embeddings, output_hidden_states=True)
```

**Comment by getao** [comment]
> Thank you for your work. However, I found that the implementation of ICAE is not the same as described in the paper.
> 
> As introduced in the paper, ICAE only uses LoRa in the encoder and freezes the decoder. <img alt="image" width="803" src="https://private-user-images.githubusercontent.com/129859769/288058288-b10dbd0f-bccf-4630-a7f3-fb05495db37b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTgyODcsIm5iZiI6MTcwMTc5Nzk4NywicGF0aCI6Ii8xMjk4NTk3NjkvMjg4MDU4Mjg4LWIxMGRiZDBmLWJjY2YtNDYzMC1hN2YzLWZiMDU0OTVkYjM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNzM5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZThlZDViNDUyMTlhYTVjNzkzM2FkMjU5MTZmNDNmMDY2OGFlZjlkNTIwY2ViNTI1NjNmMDU5NDVkOTYxN2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DvWjvnRbNvB0JbPKYVVyMFyvtdP07Do5-AVpGZ_SlIE">
> 
> But in the code, LoRA+LLaMA is used as the decoder:
> 
> https://github.com/getao/icae/blob/ac08ffbfa35430efd06b50518f1c9e60d57af97f/code/icae/llama_icae_modeling.py#L114
> 
> 
> https://github.com/getao/icae/blob/ac08ffbfa35430efd06b50518f1c9e60d57af97f/code/icae/llama_icae_modeling.py#L157-L160

Thank you for your interest. I suggest you check the difference between the line 148 and 157. You'll understand after checking.

**Comment by fafeeeeee** [comment]
Thanks for your response.

I found `peft` and `LlamaForCausalLM` are modified to support `use_lora` flag. Can I ask why not directly use the implementation like `with model.disable_adapter()` from `peft` to disable lora?  Is there something wrong with `disable_adapter` ?

**Comment by getao** [comment]
> Thanks for your response.
> 
> I found `peft` and `LlamaForCausalLM` are modified to support `use_lora` flag. Can I ask why not directly use the implementation like `with model.disable_adapter()` from `peft` to disable lora? Is there something wrong with `disable_adapter` ?

I think they should be the same -- just different implementations. We modified peft not only for the icae work but also for others.

**Comment by fafeeeeee** [comment]
Thank you
