### ISSUE TITLE
Can you release the training script for replication?

### ISSUE THREAD

**Issue by HuFY-dev** [getao/icae#5]
Hi, thanks for the awesome work you did! It is very inspiring! I wanted to replicate your work and possibly do some follow-up research, but I can't find your training scripts both for pretraining on the PILE and the finetuning process. I saw in another issue that you are organizing the code, I wonder when will the organized code be released? Thanks in advance for your help!

**Comment by getao** [comment]
It will be released soon.

**Comment by getao** [comment]
Updated in the v2 repo.
