### ISSUE TITLE
the decoder of ICAE has lora parameters

### ISSUE THREAD

**Issue by ZongqianLi** [getao/icae#7]
in 157 lline of llama_icae_modeling.py:
decoder_outputs = self.icae(inputs_embeds=decoder_input_embeddings, output_hidden_states=True)
here, icae has lora parameters, because it has been added lora parameters in line 114:
self.icae = get_peft_model(self.icae, lora_config)
and has been enabled in line 148:
compress_outputs = self.icae(inputs_embeds=autoencoder_input_embedding, output_hidden_states=True, enable_lora=True)
however, the decoder of icae should be the same as llama-2-7b and should not have lora parameters
is this a bug?

**Comment by getao** [comment]
We modify the forward of the model to use an argument enable_lora to control whether to enable the lora part.

In the latest v2 release, we use the official peft's disable_adapter to control the behavior.
